#' Create INDICATE ZIP file from mapping CSV
#'
#' @description
#' This script creates an INDICATE-format ZIP file from the most recent mapping CSV.
#' Reads configuration from mappings_list.json for metadata.
#'
#' @details
#' Run from project root:
#' Rscript inst/scripts/llm_create_indicate_zip.R ~/indicate_files [author_name]
#'
#' If author_name is not provided, defaults to "LLM"

library(jsonlite)
library(zip)

args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 1) {
  stop("Usage: Rscript llm_create_indicate_zip.R <app_folder> [author_name]")
}

app_folder <- path.expand(args[1])
author_name <- if (length(args) >= 2) args[2] else "LLM"

# Find the most recent mapping CSV file
mapping_dir <- file.path(app_folder, "concept_mapping")
mapping_files <- list.files(mapping_dir, pattern = "^mapping_.*\\.csv$", full.names = TRUE)

if (length(mapping_files) == 0) {
  stop("No mapping CSV files found. Run llm_create_mapping_csv.R first.")
}

# Get the most recent file by modification time
file_info <- file.info(mapping_files)
most_recent_idx <- which.max(file_info$mtime)
mapping_csv_path <- mapping_files[most_recent_idx]

# Extract timestamp from filename (format: mapping_YYYY-MM-DD_HH-MM-SS.csv)
timestamp <- sub("^mapping_(.+)\\.csv$", "\\1", basename(mapping_csv_path))

cat("Using mapping file:", basename(mapping_csv_path), "\n")

# Read configuration
config_path <- file.path(app_folder, "concept_mapping", "mappings_list.json")
config <- fromJSON(config_path)

# Read mapping CSV
mappings_raw <- read.csv(mapping_csv_path, stringsAsFactors = FALSE)

# Create source_concepts.csv
source_concepts <- data.frame(
  row_id = seq_len(nrow(mappings_raw)),
  vocabulary_id = mappings_raw$source_vocabulary_id,
  concept_code = mappings_raw$source_concept_code,
  concept_name = mappings_raw$source_concept_name,
  category = ifelse(!is.null(config$category), config$category, ""),
  stringsAsFactors = FALSE
)

# Create mappings.csv (INDICATE format)
mappings_export <- data.frame(
  mapping_id = seq_len(nrow(mappings_raw)),
  row_id = seq_len(nrow(mappings_raw)),
  target_general_concept_id = NA_integer_,
  target_omop_concept_id = mappings_raw$target_concept_id,
  target_custom_concept_id = NA_integer_,
  mapping_datetime = format(Sys.time(), "%Y-%m-%d %H:%M:%S"),
  user_first_name = author_name,
  user_last_name = "",
  vocabulary_id = mappings_raw$source_vocabulary_id,
  concept_code = mappings_raw$source_concept_code,
  confidence_score = mappings_raw$confidence_score,
  stringsAsFactors = FALSE
)

# Create evaluations.csv (empty)
evaluations <- data.frame(
  mapping_id = integer(),
  is_approved = integer(),
  comment = character(),
  evaluated_at = character(),
  user_first_name = character(),
  user_last_name = character(),
  stringsAsFactors = FALSE
)

# Create comments.csv
has_comment <- !is.na(mappings_raw$comments) & mappings_raw$comments != ""
if (any(has_comment)) {
  comments <- data.frame(
    mapping_id = which(has_comment),
    comment = mappings_raw$comments[has_comment],
    created_at = format(Sys.time(), "%Y-%m-%d %H:%M:%S"),
    user_first_name = author_name,
    user_last_name = "",
    stringsAsFactors = FALSE
  )
} else {
  comments <- data.frame(
    mapping_id = integer(),
    comment = character(),
    created_at = character(),
    user_first_name = character(),
    user_last_name = character(),
    stringsAsFactors = FALSE
  )
}

# Create metadata.json
metadata <- list(
  format_version = "1.0",
  format_type = "INDICATE_DATA_DICTIONARY",
  export_date = format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ"),
  exported_by = author_name,
  alignment = list(
    name = ifelse(!is.null(config$alignment_name), config$alignment_name, "LLM Mapping"),
    description = ifelse(!is.null(config$description), config$description, "Mapping generated by LLM"),
    source_vocabulary = ifelse(nrow(mappings_raw) > 0, mappings_raw$source_vocabulary_id[1], "")
  ),
  statistics = list(
    total_source_concepts = nrow(source_concepts),
    total_mappings = sum(!is.na(mappings_export$target_omop_concept_id))
  )
)

# Create ZIP
temp_dir <- tempfile(pattern = "indicate_export_")
dir.create(temp_dir)

write_json(metadata, file.path(temp_dir, "metadata.json"), pretty = TRUE, auto_unbox = TRUE)
write.csv(source_concepts, file.path(temp_dir, "source_concepts.csv"), row.names = FALSE)
write.csv(mappings_export, file.path(temp_dir, "mappings.csv"), row.names = FALSE)
write.csv(evaluations, file.path(temp_dir, "evaluations.csv"), row.names = FALSE)
write.csv(comments, file.path(temp_dir, "comments.csv"), row.names = FALSE)

zip_filename <- sprintf("indicate_mapping_%s.zip", timestamp)
zip_path <- file.path(app_folder, "concept_mapping", zip_filename)

old_wd <- getwd()
setwd(temp_dir)
zip::zip(zip_path, files = c("metadata.json", "source_concepts.csv", "mappings.csv", "evaluations.csv", "comments.csv"))
setwd(old_wd)

unlink(temp_dir, recursive = TRUE)

cat("INDICATE ZIP created:", zip_path, "\n")
cat("Author:", author_name, "\n")
